/* DO NOT manually edit this file.
It is auto-generated by db-generator.py. */

const songs_list = {
    "Light of Hope 1": "audio/Light of Hope 1.mp3"
};

const poems_list = {
    "1": [
        "The Lord is my shepherd; I shall not want.\nHe makes me lie down in green pastures.\nHe leads me beside still waters.\nHe restores my soul.\nHe leads me in paths of righteousness.\nEven though I walk through the valley of the shadow of death,\nI will fear no evil,\nfor you are with me;\nyour rod and your staff,\nthey comfort me.\n",
        "An\u00edr\u00edn min t\u00ebn\u00e1l, min l\u00fcm\u00edn ner\u00f6n;\nT\u00e9lim min and\u00f9n l\u00e9 ten\u00eb vin,\nT\u00e9lim min n\u00e9ran, vala\u00eb gen\u00fcv\u00ecel,\nT\u00e9lim min finw\u00eb l\u00e9 num\u00e1r n\u00ebrim,\nT\u00e9lim min il\u00ebm\u00edn v\u00e4n\u00e8.\n\nC\u00e4n min eh\u00e4n\u00eb l\u00f6hirim n\u00e1mh\u00e4n\u00e8,\nMin l\u00e1n ul\u00f9n h\u00e4n\u00e8,\n\u00c1l nim l\u00e9 min;\nNim n\u00e9l n\u00fal nim eren\u00fal,\nH\u00e4nlim min gild\u00e4n\u00eb.\n"
    ]
};
